In [2]:
#membuat variable dengan nama ClubEropa dengan tipe data dictionary 4 key (nama_club, pelatih_club, Negara, pemain), yang masing-masing nya memiliki 4 value

ClubEropa = {"nama_club" : ["FC Barcelona", "Arsenal", "MU", "Chelsea"],
            "pelatih_club" : ["Thomas", "Jurgen", "Guardiola", "Diego"],
            "Negara" : ["Spanyol", "Inggris", "Belanda", "Jerman"],
            "pemain" : ["Pepe", "Helen", "Giovanni", "Samuel"]}
            
print(ClubEropa)

#menambah key “sponsor” pada variabel ClubEropa yang tentunya memiliki 4 value.
sponsor = {"sponsor" : ["baju", "jersey", "celana", "sepatu"]}
ClubEropa.update(sponsor)
print(ClubEropa)

#Buatlah 4 variable array yang memiliki 5 elemen angka pada masing-masing nya (bebas nama array dan elemennya), kemudian lakukan:
import numpy as np

a = np.array([5, 10, 15, 20, 25])
b = np.array([8, 13, 18, 99, 188])
c = np.array([10, 23, 15, 65, 25])
d = np.array([6, 25, 16, 45, 250])

print(a)
print(b)
print(c)
print(d)
#a. Perkalian pada variable array 1 dengan variable array 3
print(a*c)
#b. Penjumlahan pada variable array 2 dengan variable array 4
print(b+d)
#b. Jika ada irisan, dapatkan irisan pada variable 1 dengan 4
print(np.intersect1d(a,d))

#c. Ambil nilai pada urutan ke 1, 3, dan 5 pada variabel kedua
print(b[0])
print(b[2])
print(b[4])
#4. Buatlah variabel nilai_kelas dari 4 kelas berbeda, dimana masing-masing kelas berisi nilai 4 siswa,
import numpy as np
nilai_kelas1 = np.array([50,55,87,100])
nilai_kelas2 = np.array([60,58,58,96])
nilai_kelas3 = np.array([59,85,35,65])
nilai_kelas4 = np.array([90,80,60,40])
print(nilai_kelas1)
print(nilai_kelas2)
print(nilai_kelas3)
print(nilai_kelas4)
# kemudian kurangi semua nilai siswa dengan 5 sebagai nilai hukuman karena menyontek
print(nilai_kelas1-5)
print(nilai_kelas2-5)
print(nilai_kelas3-5)
print(nilai_kelas4-5)
#5. jelaskan sejarah python, keunggulan dan apa kegunaannya?
Python diciptakan oleh Guido van Rossum pertama kali di  Centrum Wiskunde & Informatica (CWI) di Belanda pada awal tahun 1990-an. Bahasa python terinspirasi dari bahasa pemrograman ABC. Sampai sekarang, Guido masih menjadi penulis utama untuk python, meskipun bersifat open source sehingga ribuan orang juga berkontribusi dalam mengembangkannya.Di tahun 1995, Guido melanjutkan pembuatan python di Corporation for National Research Initiative (CNRI) di Virginia Amerika, di mana dia merilis beberapa versi dari python. Pada Mei 2000, Guido dan tim Python pindah ke BeOpen.com dan membentuk tim BeOpen PythonLabs. Di bulan Oktober pada tahun yang sama, tim python pindah ke Digital Creation (sekarang menjadi Perusahaan Zope). Pada tahun 2001, dibentuklah Organisasi Python yaitu Python Software Foundation (PSF). PSF merupakan organisasi nirlaba yang dibuat khusus untuk semua hal yang berkaitan dengan hak intelektual Python.
(sumber: Pythonindo)
Keunggulan menggunakan python yaitu: 
1. python memiliki struktur syntax yang sama; 
2. Python juga memiliki bahasa pemograman yang portable yang dimana pengguna tidak perlu menuliskan kode berulang kali; 
3. Python memiliki pustaka atau ibrary yang luas; 
4. Python juga disebut sebagai interpreter language yang dimana kode-kode yang Anda tuliskan akan langsung diterjemahkan lewat baris per baris; 
5. Python juga bersifat open source. Lisensi open source ini telah disetujui oleh OSI (Open Source Initiative). Lisensi ini juga diatur oleh Python Software Foundation; 
(sumber: Alterra Academy)
Kegunaan Python:
1. Untuk mengolah data yang jumlahnya sangat besar (jutaan atau lebih);
2. Pengembangan machine learning, 
3. Penggunaan dalam fintech (financial technology) dimana dengan menggunakan Python, aplikasi dan berbagai fitur yang ada di fintech akan lebih aman.
(sumber: Glints)

{'nama_club': ['FC Barcelona', 'Arsenal', 'MU', 'Chelsea'], 'pelatih_club': ['Thomas', 'Jurgen', 'Guardiola', 'Diego'], 'Negara': ['Spanyol', 'Inggris', 'Belanda', 'Jerman'], 'pemain': ['Pepe', 'Helen', 'Giovanni', 'Samuel']}
{'nama_club': ['FC Barcelona', 'Arsenal', 'MU', 'Chelsea'], 'pelatih_club': ['Thomas', 'Jurgen', 'Guardiola', 'Diego'], 'Negara': ['Spanyol', 'Inggris', 'Belanda', 'Jerman'], 'pemain': ['Pepe', 'Helen', 'Giovanni', 'Samuel'], 'sponsor': ['baju', 'jersey', 'celana', 'sepatu']}
[ 5 10 15 20 25]
[  8  13  18  99 188]
[10 23 15 65 25]
[  6  25  16  45 250]
[  50  230  225 1300  625]
[ 14  38  34 144 438]
[25]
8
18
188
[ 50  55  87 100]
[60 58 58 96]
[59 85 35 65]
[90 80 60 40]
[45 50 82 95]
[55 53 53 91]
[54 80 30 60]
[85 75 55 35]
